copyright: >
  Copyright &copy; 2023 - 2025 Daniel Bodky - <a href="#__consent">Change cookie settings</a>
extra:
  analytics:
    feedback:
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!
      title: Was this page helpful?
    property: !ENV [GTAG, '']
    provider: google
  consent:
    actions:
      - accept
      - manage
      - reject
    description: >-
      I use cookies to recognize your repeated visits and preferences, as well as to measure which kind of content
      you like, which pages you found useful (or not!), and what might be missing or unclear.
    title: Cookie consent
  generator: true
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/daniel-bodky
      name: Linkedin
    - icon: fontawesome/brands/github
      link: https://github.com/mocdaniel
      name: GitHub
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/dbodky.me
      name: Bluesky
# Custom CSS
extra_css:
  - stylesheets/extra.css
  - stylesheets/general.css
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
# Homepage configuration
nav:
  - Home: index.md
  - About Me: about.md
  - Blog:
      - Blog Overview: blog/index.md
repo_name: mocdaniel/dbodky.me
repo_url: https://github.com/mocdaniel/dbodky.me
plugins:
  - blog:
      authors_profiles: true
      categories_allowed:
        - Cloud Native
        - Homelab
        - Kubernetes
        - Tutorials
      post_date_format: medium
      post_excerpt: required
      post_url_format: "{slug}"
  - optimize:
      enabled: !ENV [CI, false]
  - privacy:
      enabled: !ENV [CI, false]
  - search
  - social
  - typeset
site_name: dbodky.me
site_url: https://dbodky.me
site_description: Daniel's Personal Webspace
site_author: Daniel Bodky
theme:
  custom_dir: overrides/
  features:
    - content.code.copy
    - content.footnote.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
  font:
    text: Roboto
    code: Fira Code
  icon:
    logo: fontawesome/solid/code
    repo: fontawesome/brands/github
  name: material
  palette:
    scheme: slate
    primary: custom
    accent: custom
