authors:
  daniel:
    name: Daniel Bodky
    description: Developer Advocate and curious technologist
    avatar: assets/images/daniel.jpg
    slug: https://github.com/mocdaniel.png
    url: https://dbodky.me
